### ISSUE TITLE
feat: sidecars

### ISSUE THREAD

**Issue by Silthus** [helmless/google-cloudrun-charts#4]
The only missing feature in the Helmless charts for Cloud Run right now are [sidecars](https://cloud.google.com/run/docs/deploying#yaml_2). 

When implementing this it makes sense to swap the current schema with one that is more aligned with the standard K8s multi container schema for a single pod. The pod being the Google Cloud Run Service in this case. One restriction however applies: only one container can have an ingress port defined in the `ports` section. The other containers can listen to ports bound to the localhost of the pod using the `PORT` env variable. See this [ngnix example](https://cloud.google.com/run/docs/internet-proxy-nginx-sidecar) for an ingress sidecar.

Sidecars can also have [dependencies (a startup order)](https://cloud.google.com/run/docs/configuring/containers#container-ordering) that can be defined using the `run.googleapis.com/container-dependencies: '{"CONTAINER1":["CONTAINER2"], "CONTAINER3":["CONTAINER1","CONTAINER2"]}'` at the template level. If set every sidecar needs to provide health checks that determine the successful startup of a container.

To still allow merging values every sidecar should be configured under a unique key. 

```yaml
# allow shared env and secrets for all containers
# can be overwritten at the container level
env:
  COLOR: "BLUE"

# ingressContainer: app # default container to use for external ingress binding

containers:
  app: # default application sidecar
    port: 8080 # cloud run always only allows to bind to a single port
    dependsOn:
      - init
    env:
      SOME_VAR: "something"
    ...
  init: # custom sidecar
    env:
      COLOR: "RED"
    ...

```

---

*Cloud Run Jobs do not support sidecars.*
